export const startingBalance = 8500

export const initialTransactions = [
  {
    id: 'txn-001',
    date: '2026-01-03',
    description: 'Monthly salary',
    category: 'Salary',
    type: 'income',
    amount: 5800,
    note: 'Primary paycheck',
  },
  {
    id: 'txn-002',
    date: '2026-01-08',
    description: 'Rent payment',
    category: 'Housing',
    type: 'expense',
    amount: 1800,
  },
  {
    id: 'txn-003',
    date: '2026-01-10',
    description: 'Groceries',
    category: 'Groceries',
    type: 'expense',
    amount: 410,
  },
  {
    id: 'txn-004',
    date: '2026-01-12',
    description: 'Design contract',
    category: 'Freelance',
    type: 'income',
    amount: 860,
    note: 'Landing page work',
  },
  {
    id: 'txn-005',
    date: '2026-01-16',
    description: 'Utilities',
    category: 'Housing',
    type: 'expense',
    amount: 185,
  },
  {
    id: 'txn-006',
    date: '2026-01-22',
    description: 'Dinner with clients',
    category: 'Dining',
    type: 'expense',
    amount: 96,
  },
  {
    id: 'txn-007',
    date: '2026-01-25',
    description: 'Project software',
    category: 'Subscriptions',
    type: 'expense',
    amount: 29,
  },
  {
    id: 'txn-008',
    date: '2026-02-03',
    description: 'Monthly salary',
    category: 'Salary',
    type: 'income',
    amount: 5800,
  },
  {
    id: 'txn-009',
    date: '2026-02-07',
    description: 'Rent payment',
    category: 'Housing',
    type: 'expense',
    amount: 1800,
  },
  {
    id: 'txn-010',
    date: '2026-02-10',
    description: 'Groceries',
    category: 'Groceries',
    type: 'expense',
    amount: 450,
  },
  {
    id: 'txn-011',
    date: '2026-02-12',
    description: 'Dividend payout',
    category: 'Investments',
    type: 'income',
    amount: 220,
  },
  {
    id: 'txn-012',
    date: '2026-02-18',
    description: 'Weekend trip',
    category: 'Travel',
    type: 'expense',
    amount: 620,
  },
  {
    id: 'txn-013',
    date: '2026-02-21',
    description: 'Metro and rides',
    category: 'Transport',
    type: 'expense',
    amount: 142,
  },
  {
    id: 'txn-014',
    date: '2026-02-25',
    description: 'Wellness class',
    category: 'Wellness',
    type: 'expense',
    amount: 88,
  },
  {
    id: 'txn-015',
    date: '2026-03-03',
    description: 'Monthly salary',
    category: 'Salary',
    type: 'income',
    amount: 5800,
  },
  {
    id: 'txn-016',
    date: '2026-03-06',
    description: 'Rent payment',
    category: 'Housing',
    type: 'expense',
    amount: 1800,
  },
  {
    id: 'txn-017',
    date: '2026-03-09',
    description: 'Groceries',
    category: 'Groceries',
    type: 'expense',
    amount: 385,
  },
  {
    id: 'txn-018',
    date: '2026-03-11',
    description: 'Consulting retainer',
    category: 'Freelance',
    type: 'income',
    amount: 1240,
  },
  {
    id: 'txn-019',
    date: '2026-03-15',
    description: 'Insurance premium',
    category: 'Insurance',
    type: 'expense',
    amount: 210,
  },
  {
    id: 'txn-020',
    date: '2026-03-19',
    description: 'Team lunch',
    category: 'Dining',
    type: 'expense',
    amount: 138,
  },
  {
    id: 'txn-021',
    date: '2026-03-23',
    description: 'Subscription renewals',
    category: 'Subscriptions',
    type: 'expense',
    amount: 29,
  },
  {
    id: 'txn-022',
    date: '2026-04-03',
    description: 'Monthly salary',
    category: 'Salary',
    type: 'income',
    amount: 5800,
  },
  {
    id: 'txn-023',
    date: '2026-04-05',
    description: 'Rent payment',
    category: 'Housing',
    type: 'expense',
    amount: 1800,
  },
  {
    id: 'txn-024',
    date: '2026-04-07',
    description: 'Groceries',
    category: 'Groceries',
    type: 'expense',
    amount: 430,
  },
  {
    id: 'txn-025',
    date: '2026-04-09',
    description: 'App design sprint',
    category: 'Freelance',
    type: 'income',
    amount: 680,
  },
  {
    id: 'txn-026',
    date: '2026-04-14',
    description: 'Conference travel',
    category: 'Travel',
    type: 'expense',
    amount: 740,
  },
  {
    id: 'txn-027',
    date: '2026-04-18',
    description: 'Utilities',
    category: 'Housing',
    type: 'expense',
    amount: 205,
  },
  {
    id: 'txn-028',
    date: '2026-04-21',
    description: 'Dinner out',
    category: 'Dining',
    type: 'expense',
    amount: 112,
  },
  {
    id: 'txn-029',
    date: '2026-04-25',
    description: 'Quarterly tax payment',
    category: 'Taxes',
    type: 'expense',
    amount: 310,
  },
]